CLASS zcl_abaplint_configuration DEFINITION
  PUBLIC
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_ABAPLINT_CONFIGURATION IMPLEMENTATION.
ENDCLASS.
